# Artificial Neural Network

### Importing the libraries

In [1]:
#!pip install tensorflow

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

adding units is based on trail and error, we may try with 6, 7,8 
whichever gives based result use them

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

Since sigmoid gives probability, the ans >= 0.5 is true ans < 0.5 is false
we are using this sigmoid function in o/p layer because our o/p is binary classification o or 1, but if it has multiple classes, then the activation function should be softmax

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

adam optimizer is used, it uses stochastic gradient descent, 

in our example the classification is binary classification, then loss function is binary-crossentropy, 

if it has more than 2 classes then use chategorical cross entropy

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

to create mini batch stochastic gradient, we are choosing the default 
batch size which is usually used is 32. but we may change it. epochs

In [19]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 994us/step - loss: 0.5640 - accuracy: 0.7794
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4715 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 917us/step - loss: 0.4462 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 929us/step - loss: 0.4378 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 927us/step - loss: 0.4332 - accuracy: 0.7961
Epoch 6/100
250/250 [==============================] - 0s 866us/step - loss: 0.4297 - accuracy: 0.7990
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4263 - accuracy: 0.8049
Epoch 8/100
250/250 [==============================] - 0s 947us/step - loss: 0.4229 - accuracy: 0.8096
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4195 - accuracy: 0.8121
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4

250/250 [==============================] - 0s 974us/step - loss: 0.3346 - accuracy: 0.8626
Epoch 81/100
250/250 [==============================] - 0s 878us/step - loss: 0.3347 - accuracy: 0.8630
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3343 - accuracy: 0.8639
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8633
Epoch 84/100
250/250 [==============================] - 0s 928us/step - loss: 0.3345 - accuracy: 0.8620
Epoch 85/100
250/250 [==============================] - 0s 892us/step - loss: 0.3339 - accuracy: 0.8622
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3347 - accuracy: 0.8625
Epoch 87/100
250/250 [==============================] - 0s 984us/step - loss: 0.3343 - accuracy: 0.8626
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3343 - accuracy: 0.8629
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3340 - 

In [20]:
ann.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (32, 6)                   78        
                                                                 
 dense_1 (Dense)             (32, 6)                   42        
                                                                 
 dense_2 (Dense)             (32, 1)                   7         
                                                                 
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [21]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 75ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [22]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 678us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1512   83]
 [ 197  208]]


0.86